sudo: required
language: elixir
elixir:
  - '1.10'
opt_release: '22.2.6'

addons:
  postgres: "9.4"

services:
  - postgresql
  - docker
env:
  global:
    - GCP_PROJECT_ID=blissful-star-318316
    - IMAGE=gcr.io/blissful-star-318316/findmy_personal
    - CLOUD_RUN_SERVICE=blissful-star-318316
    - CLOUD_RUN_REGION=us-central1
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SHA=$(git rev-parse HEAD)

cache:
  directories:
    - _build
    - deps
before_install:
  - openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv -in google-key.json.enc -out google-key.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null #Download SDK GOOGLE CI/CDCloudRuneElixir2  
  - source "$HOME/google-cloud-sdk/path.bash.inc"   
  - gcloud auth activate-service-account --key-file=google-key.json 
  - gcloud auth configure-docker # habilita push para o gcr  
  - gcloud config set project "${GCP_PROJECT_ID}"  
  - gcloud components install beta # until Cloud Run is generally available (GA)# install: true # no-op
before_script:  
  - mix local.hex --force  
  - mix local.rebar --force  
  - mix do deps.get, deps.compile
  #- mix do ecto.create, ecto.migrat

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main


# openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv -in google-key.json.enc -out google-key.json -d

# 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