sudo: required
language: elixir
elixir:
  - '1.10'
opt_release: '22.2.6'

addons:
  postgres: "9.4"

services:
  - postgresql
  - docker
env:
  global:
    - GCP_PROJECT_ID=blissful-star-318316
    - IMAGE=gcr.io/blissful-star-318316/findmy_personal
    - CLOUD_RUN_SERVICE=blissful-star-318316
    - CLOUD_RUN_REGION=us-central1
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SHA=$(git rev-parse HEAD)

cache:
  directories:
    - _build
    - deps
script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json


# openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv -in google-key.json.enc -out google-key.json -d

# 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